// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce.Inventory.Infrastructure.Persistence;

#nullable disable

namespace eCommerce.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260827163554_AddAutoPricing")]
    partial class AddAutoPricing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blueprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardMarketIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardTraderId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditableProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpansionId")
                        .HasColumnType("int");

                    b.Property<string>("FixedProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItalianName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Rarity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TcgPlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardTraderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Blueprint_CardTraderId");

                    b.HasIndex("ExpansionId")
                        .HasDatabaseName("IX_Blueprint_ExpansionId");

                    b.HasIndex("GameId")
                        .HasDatabaseName("IX_Blueprint_GameId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Blueprint_Name");

                    b.HasIndex("GameId", "ExpansionId")
                        .HasDatabaseName("IX_Blueprint_GameId_ExpansionId");

                    b.ToTable("Blueprints");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardTraderId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Expansion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageCardValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgValueCommon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgValueMythic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgValueRare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgValueUncommon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BoxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CardTraderId")
                        .HasColumnType("int");

                    b.Property<int?>("CardsPerPack")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("IconSvgUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastValueAnalysisUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PacksPerBox")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalMinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Expansions");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.ExpansionROI", b =>
                {
                    b.Property<decimal?>("Differenza")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExpansionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotaleAcquistato")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotaleVenduto")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("ExpansionsROI", (string)null);
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardTraderId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlueprintId")
                        .HasColumnType("int");

                    b.Property<int?>("CardTraderProductId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAltered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ListingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddressJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("BuyerUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardTraderOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SellerFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellerSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellerTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddressJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlueprintId")
                        .HasColumnType("int");

                    b.Property<int>("CardTraderId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpansionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAltered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserDataField")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PendingListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlueprintId")
                        .HasColumnType("int");

                    b.Property<int?>("CardTraderProductId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GradingCentering")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GradingConditionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GradingConfidence")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GradingCorners")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GradingEdges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GradingImagesCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("GradingScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GradingSurface")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SyncError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PendingListing_CreatedAt");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("IsSynced")
                        .HasDatabaseName("IX_PendingListing_IsSynced");

                    b.ToTable("PendingListings");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PriceChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlueprintId")
                        .HasColumnType("int");

                    b.Property<int>("ComparableOffersCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("OutliersRejectedCount")
                        .HasColumnType("int");

                    b.Property<int?>("PricingRuleId")
                        .HasColumnType("int");

                    b.Property<int?>("PricingRunLogId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProposedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("ReferencePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Trigger")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PriceChangeLog_CreatedAt");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("PricingRunLogId");

                    b.HasIndex("BlueprintId", "CreatedAt")
                        .HasDatabaseName("IX_PriceChangeLog_Blueprint_CreatedAt");

                    b.ToTable("PriceChangeLogs");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCodesCsv")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DryRun")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableOutlierRejection")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeAltered")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeGraded")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeSigned")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeVacationSellers")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeNormalSellers")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeProSellers")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MatchCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("MatchFoil")
                        .HasColumnType("bit");

                    b.Property<bool>("MatchLanguage")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxChangePercentPerRun")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("MinComparableOffers")
                        .HasColumnType("int");

                    b.Property<int>("MinOffersForOutlierRejection")
                        .HasColumnType("int");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinSellerDailyCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("OutlierMadThreshold")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PricingProfiles");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdjustmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdjustmentPercent")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("CanDecrease")
                        .HasColumnType("bit");

                    b.Property<bool>("CanIncrease")
                        .HasColumnType("bit");

                    b.Property<decimal>("FromPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("PricingProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceMode")
                        .HasColumnType("int");

                    b.Property<decimal>("ToPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PricingProfileId", "FromPrice", "ToPrice")
                        .HasDatabaseName("IX_PricingRule_Profile_Range");

                    b.ToTable("PricingRules");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppliedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DryRun")
                        .HasColumnType("bit");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EvaluatedCount")
                        .HasColumnType("int");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<int>("NoChangeCount")
                        .HasColumnType("int");

                    b.Property<int>("PlannedCount")
                        .HasColumnType("int");

                    b.Property<int>("PricingProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SimulatedCount")
                        .HasColumnType("int");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPriceDelta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Trigger")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PricingProfileId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_PricingRunLog_StartedAt");

                    b.ToTable("PricingRunLogs");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PropertyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyValues");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Blueprint", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.Expansion", "Expansion")
                        .WithMany("Blueprints")
                        .HasForeignKey("ExpansionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Inventory.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expansion");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Category", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.Game", "Game")
                        .WithMany("Categories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Expansion", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.Game", "Game")
                        .WithMany("Expansions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("Blueprint", "Blueprint")
                        .WithMany("InventoryItems")
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blueprint");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Blueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId");

                    b.HasOne("eCommerce.Inventory.Domain.Entities.InventoryItem", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("InventoryItemId");

                    b.HasOne("eCommerce.Inventory.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blueprint");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PendingListing", b =>
                {
                    b.HasOne("Blueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eCommerce.Inventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Blueprint");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PriceChangeLog", b =>
                {
                    b.HasOne("Blueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("eCommerce.Inventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Inventory.Domain.Entities.PricingRunLog", "PricingRunLog")
                        .WithMany("Changes")
                        .HasForeignKey("PricingRunLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Blueprint");

                    b.Navigation("InventoryItem");

                    b.Navigation("PricingRunLog");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingRule", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.PricingProfile", "PricingProfile")
                        .WithMany("Rules")
                        .HasForeignKey("PricingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingProfile");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingRunLog", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.PricingProfile", "PricingProfile")
                        .WithMany()
                        .HasForeignKey("PricingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingProfile");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Property", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.Category", "Category")
                        .WithMany("Properties")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PropertyValue", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.Property", "Property")
                        .WithMany("PossibleValues")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Blueprint", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Category", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Expansion", b =>
                {
                    b.Navigation("Blueprints");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Game", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Expansions");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.InventoryItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingProfile", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingRunLog", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Property", b =>
                {
                    b.Navigation("PossibleValues");
                });
#pragma warning restore 612, 618
        }
    }
}
