// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eCommerce.Inventory.Infrastructure.Persistence;

#nullable disable

namespace eCommerce.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261009143055_FixExpansionsRoiPaidOrders")]
    partial class FixExpansionsRoiPaidOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blueprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardMarketIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardTraderId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EditableProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpansionId")
                        .HasColumnType("int");

                    b.Property<string>("FixedProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItalianName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Rarity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScryfallId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TcgPlayerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CardTraderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Blueprint_CardTraderId");

                    b.HasIndex("ExpansionId")
                        .HasDatabaseName("IX_Blueprint_ExpansionId");

                    b.HasIndex("GameId")
                        .HasDatabaseName("IX_Blueprint_GameId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Blueprint_Name");

                    b.HasIndex("GameId", "ExpansionId")
                        .HasDatabaseName("IX_Blueprint_GameId_ExpansionId");

                    b.ToTable("Blueprints");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.AlertNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlertRuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EmailRequested")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SealedProductId")
                        .HasColumnType("int");

                    b.Property<string>("SetCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AlertNotification_CreatedAt");

                    b.HasIndex("ReadAt")
                        .HasDatabaseName("IX_AlertNotification_ReadAt");

                    b.ToTable("AlertNotifications");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastEvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RecentReleaseDays")
                        .HasColumnType("int");

                    b.Property<int?>("SealedProductId")
                        .HasColumnType("int");

                    b.Property<bool>("SendEmail")
                        .HasColumnType("bit");

                    b.Property<string>("SetCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subtype")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Threshold")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<bool>("UseLowPrice")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SealedProductId");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.AlertRuleMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertRuleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchingSince")
                        .HasColumnType("datetime2");

                    b.Property<int>("SealedProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId", "SealedProductId")
                        .IsUnique()
                        .HasDatabaseName("IX_AlertRuleMatch_Rule_Product");

                    b.ToTable("AlertRuleMatches");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.BoosterConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoosterType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TotalWeight")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SetCode", "BoosterType")
                        .HasDatabaseName("IX_BoosterConfig_Set_Type");

                    b.ToTable("BoosterConfigs");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.BoosterConfigSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoosterConfigId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BoosterConfigId");

                    b.ToTable("BoosterConfigSlots");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.BoosterSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BoosterType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("TotalWeight")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SetCode", "BoosterType")
                        .HasDatabaseName("IX_BoosterSheet_Set_Type");

                    b.ToTable("BoosterSheets");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.BoosterSheetCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoosterSheetId")
                        .HasColumnType("int");

                    b.Property<Guid>("CardUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Weight")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BoosterSheetId");

                    b.ToTable("BoosterSheetCards");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.CardTraderCardPrice", b =>
                {
                    b.Property<int>("BlueprintId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<int>("OfferCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BlueprintId", "IsFoil");

                    b.ToTable("CardTraderCardPrices");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.CardmarketImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("NewProducts")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("SealedProducts")
                        .HasColumnType("int");

                    b.Property<int>("SealedSnapshotsWritten")
                        .HasColumnType("int");

                    b.Property<int>("SinglesSnapshotsWritten")
                        .HasColumnType("int");

                    b.Property<int>("SinglesTracked")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SourceCreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("SourceLastModified")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Trigger")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_CardmarketImportLog_StartedAt");

                    b.ToTable("CardmarketImportLogs");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.CardmarketLatestPrice", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("Low")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LowFoil")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Trend")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TrendFoil")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProduct");

                    b.ToTable("CardmarketLatestPrices");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.CardmarketPriceSnapshot", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("Avg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Avg1")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Avg30")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Avg7")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgFoil")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Low")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LowFoil")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Trend")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TrendFoil")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProduct", "Date");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_CardmarketPriceSnapshot_Date");

                    b.ToTable("CardmarketPriceSnapshots");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.CardmarketProduct", b =>
                {
                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<int>("IdExpansion")
                        .HasColumnType("int");

                    b.Property<bool>("IsSingle")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdProduct");

                    b.HasIndex("IdExpansion")
                        .HasDatabaseName("IX_CardmarketProduct_IdExpansion");

                    b.ToTable("CardmarketProducts");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardTraderId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Expansion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageCardValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgValueCommon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgValueMythic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgValueRare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgValueUncommon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BoxPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CardTraderId")
                        .HasColumnType("int");

                    b.Property<int?>("CardsPerPack")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("IconSvgUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastValueAnalysisUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PacksPerBox")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalMinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Expansions");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.ExpansionROI", b =>
                {
                    b.Property<string>("ExpansionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotaleVenduto")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("ExpansionsROI", (string)null);
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CardTraderId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlueprintId")
                        .HasColumnType("int");

                    b.Property<int?>("CardTraderProductId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAltered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ListingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.MtgjsonCard", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CardmarketId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Number")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rarity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ScryfallId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Uuid");

                    b.HasIndex("SetCode")
                        .HasDatabaseName("IX_MtgjsonCard_SetCode");

                    b.ToTable("MtgjsonCards");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.MtgjsonDeck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SetCode")
                        .HasDatabaseName("IX_MtgjsonDeck_SetCode");

                    b.ToTable("MtgjsonDecks");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.MtgjsonDeckCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CardUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<int>("MtgjsonDeckId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MtgjsonDeckId");

                    b.ToTable("MtgjsonDeckCards");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.MtgjsonSet", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DetailImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasBoosterData")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ParentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.HasIndex("ParentCode")
                        .HasDatabaseName("IX_MtgjsonSet_ParentCode");

                    b.ToTable("MtgjsonSets");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddressJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<string>("BuyerUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CardTraderOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SellerFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellerSubtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SellerTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddressJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BlueprintId")
                        .HasColumnType("int");

                    b.Property<int>("CardTraderId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpansionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAltered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserDataField")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PendingListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlueprintId")
                        .HasColumnType("int");

                    b.Property<int?>("CardTraderProductId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GradingCentering")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GradingConditionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("GradingConfidence")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GradingCorners")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GradingEdges")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("GradingImagesCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("GradingScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GradingSurface")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSigned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSynced")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SellingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SyncError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PendingListing_CreatedAt");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("IsSynced")
                        .HasDatabaseName("IX_PendingListing_IsSynced");

                    b.ToTable("PendingListings");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PriceChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlueprintId")
                        .HasColumnType("int");

                    b.Property<int>("ComparableOffersCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("OldPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("OutliersRejectedCount")
                        .HasColumnType("int");

                    b.Property<int?>("PricingRuleId")
                        .HasColumnType("int");

                    b.Property<int?>("PricingRunLogId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProposedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("ReferencePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ReferenceSellerPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Trigger")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PriceChangeLog_CreatedAt");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("PricingRunLogId");

                    b.HasIndex("BlueprintId", "CreatedAt")
                        .HasDatabaseName("IX_PriceChangeLog_Blueprint_CreatedAt");

                    b.ToTable("PriceChangeLogs");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PriceHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlueprintId")
                        .HasColumnType("int");

                    b.Property<int>("CardTraderProductId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("BlueprintId", "RecordedAt")
                        .HasDatabaseName("IX_PriceHistory_Blueprint_RecordedAt");

                    b.HasIndex("CardTraderProductId", "RecordedAt")
                        .HasDatabaseName("IX_PriceHistory_Product_RecordedAt");

                    b.ToTable("PriceHistoryEntries");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCodesCsv")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DryRun")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableOutlierRejection")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeAltered")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeGraded")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeSigned")
                        .HasColumnType("bit");

                    b.Property<bool>("ExcludeVacationSellers")
                        .HasColumnType("bit");

                    b.Property<decimal>("GuardrailExemptAmount")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("IncludeNormalSellers")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeOnlyCtZeroSellers")
                        .HasColumnType("bit");

                    b.Property<bool>("IncludeProSellers")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("MatchCondition")
                        .HasColumnType("bit");

                    b.Property<bool>("MatchFoil")
                        .HasColumnType("bit");

                    b.Property<bool>("MatchLanguage")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxDecreasePercentPerRun")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("MaxIncreasePercentPerRun")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("MaxMedianRatio")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("MinComparableOffers")
                        .HasColumnType("int");

                    b.Property<int>("MinOffersForOutlierRejection")
                        .HasColumnType("int");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MinSellerDailyCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("OutlierMadThreshold")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<bool>("SkipWhenFewerOffersThanPosition")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PricingProfiles");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AdjustmentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdjustmentPercent")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<bool>("CanDecrease")
                        .HasColumnType("bit");

                    b.Property<bool>("CanIncrease")
                        .HasColumnType("bit");

                    b.Property<decimal>("FromPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MinComparableOffers")
                        .HasColumnType("int");

                    b.Property<bool?>("OnlyCtZeroSellers")
                        .HasColumnType("bit");

                    b.Property<decimal>("Percentile")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("PricingProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceMode")
                        .HasColumnType("int");

                    b.Property<decimal>("ToPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PricingProfileId", "FromPrice", "ToPrice")
                        .HasDatabaseName("IX_PricingRule_Profile_Range");

                    b.ToTable("PricingRules");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingRunLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppliedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DryRun")
                        .HasColumnType("bit");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EvaluatedCount")
                        .HasColumnType("int");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<int>("NoChangeCount")
                        .HasColumnType("int");

                    b.Property<int>("PlannedCount")
                        .HasColumnType("int");

                    b.Property<int>("PricingProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SimulatedCount")
                        .HasColumnType("int");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPriceDelta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Trigger")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PricingProfileId");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("IX_PricingRunLog_StartedAt");

                    b.ToTable("PricingRunLogs");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.ProductPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateOnly?>("OpenedAt")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PredictedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PredictedOpenValueNet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PredictionCoverage")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateOnly?>("PurchasedAt")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SealedProductId")
                        .HasColumnType("int");

                    b.Property<string>("Seller")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Store")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SealedProductId");

                    b.HasIndex("Tag")
                        .HasDatabaseName("IX_ProductPurchase_Tag");

                    b.ToTable("ProductPurchases");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PropertyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyValues");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.SealedOpportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CmLow")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CmTrend")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CoverageCm")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Decision")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("MainSetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("OpenValueCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OpeningRoiPercent")
                        .HasPrecision(9, 1)
                        .HasColumnType("decimal(9,1)");

                    b.Property<decimal?>("SealedNetCm")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SealedProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .HasDatabaseName("IX_SealedOpportunity_Date");

                    b.HasIndex("SealedProductId", "Date")
                        .HasDatabaseName("IX_SealedOpportunity_Product_Date");

                    b.ToTable("SealedOpportunities");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.SealedProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CardCount")
                        .HasColumnType("int");

                    b.Property<int?>("CardTraderBlueprintId")
                        .HasColumnType("int");

                    b.Property<int?>("CardmarketId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CtMinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CtOfferCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CtPriceUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Subtype")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CardmarketId")
                        .HasDatabaseName("IX_SealedProduct_CardmarketId");

                    b.HasIndex("SetCode")
                        .HasDatabaseName("IX_SealedProduct_SetCode");

                    b.HasIndex("Uuid")
                        .IsUnique()
                        .HasDatabaseName("IX_SealedProduct_Uuid");

                    b.ToTable("SealedProducts");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.SealedProductContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ChildUuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<bool?>("Foil")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PackCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SealedProductId")
                        .HasColumnType("int");

                    b.Property<string>("SetCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("SealedProductId");

                    b.ToTable("SealedProductContents");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.SecretLairShopCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SecretLairShopProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SecretLairShopProductId");

                    b.ToTable("SecretLairShopCards");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.SecretLairShopProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ContentsFetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DropName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("EstimatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EstimatedNetValue")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFoil")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPreorder")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LimitPerCustomer")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("RefId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset?>("ReleaseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SaleEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SaleStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SoldOutAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("WizardsProductId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("WizardsProductId")
                        .IsUnique();

                    b.ToTable("SecretLairShopProducts");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.SecretLairShopRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ContentsFetched")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("NewProducts")
                        .HasColumnType("int");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.Property<int>("Products")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("SecretLairShopRuns");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Blueprint", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.Expansion", "Expansion")
                        .WithMany("Blueprints")
                        .HasForeignKey("ExpansionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eCommerce.Inventory.Domain.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expansion");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.AlertNotification", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.AlertRule", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.SealedProduct", "SealedProduct")
                        .WithMany()
                        .HasForeignKey("SealedProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SealedProduct");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.AlertRuleMatch", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.BoosterConfigSlot", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.BoosterConfig", "BoosterConfig")
                        .WithMany("Slots")
                        .HasForeignKey("BoosterConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoosterConfig");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.BoosterSheetCard", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.BoosterSheet", "BoosterSheet")
                        .WithMany("Cards")
                        .HasForeignKey("BoosterSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoosterSheet");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Category", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.Game", "Game")
                        .WithMany("Categories")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Expansion", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.Game", "Game")
                        .WithMany("Expansions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.InventoryItem", b =>
                {
                    b.HasOne("Blueprint", "Blueprint")
                        .WithMany("InventoryItems")
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blueprint");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.MtgjsonDeckCard", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.MtgjsonDeck", "MtgjsonDeck")
                        .WithMany("Cards")
                        .HasForeignKey("MtgjsonDeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MtgjsonDeck");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("Blueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId");

                    b.HasOne("eCommerce.Inventory.Domain.Entities.InventoryItem", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("InventoryItemId");

                    b.HasOne("eCommerce.Inventory.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blueprint");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PendingListing", b =>
                {
                    b.HasOne("Blueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eCommerce.Inventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Blueprint");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PriceChangeLog", b =>
                {
                    b.HasOne("Blueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("eCommerce.Inventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("eCommerce.Inventory.Domain.Entities.PricingRunLog", "PricingRunLog")
                        .WithMany("Changes")
                        .HasForeignKey("PricingRunLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Blueprint");

                    b.Navigation("InventoryItem");

                    b.Navigation("PricingRunLog");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PriceHistoryEntry", b =>
                {
                    b.HasOne("Blueprint", "Blueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("eCommerce.Inventory.Domain.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Blueprint");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingRule", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.PricingProfile", "PricingProfile")
                        .WithMany("Rules")
                        .HasForeignKey("PricingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingProfile");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingRunLog", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.PricingProfile", "PricingProfile")
                        .WithMany()
                        .HasForeignKey("PricingProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingProfile");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.ProductPurchase", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.SealedProduct", "SealedProduct")
                        .WithMany()
                        .HasForeignKey("SealedProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SealedProduct");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Property", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.Category", "Category")
                        .WithMany("Properties")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PropertyValue", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.Property", "Property")
                        .WithMany("PossibleValues")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.SealedOpportunity", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.SealedProduct", "SealedProduct")
                        .WithMany()
                        .HasForeignKey("SealedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SealedProduct");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.SealedProductContent", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.SealedProduct", "SealedProduct")
                        .WithMany("Contents")
                        .HasForeignKey("SealedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SealedProduct");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.SecretLairShopCard", b =>
                {
                    b.HasOne("eCommerce.Inventory.Domain.Entities.SecretLairShopProduct", "Product")
                        .WithMany("Cards")
                        .HasForeignKey("SecretLairShopProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Blueprint", b =>
                {
                    b.Navigation("InventoryItems");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.BoosterConfig", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.BoosterSheet", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Category", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Expansion", b =>
                {
                    b.Navigation("Blueprints");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Game", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Expansions");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.InventoryItem", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.MtgjsonDeck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingProfile", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.PricingRunLog", b =>
                {
                    b.Navigation("Changes");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.Property", b =>
                {
                    b.Navigation("PossibleValues");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.SealedProduct", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("eCommerce.Inventory.Domain.Entities.SecretLairShopProduct", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
